name: Deploy Team PHP Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.actor == 'SyedJasmine1991' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Team server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2222
          debug: true
          script: |
           whoami
            hostname

            cd /home/team/public_html || exit 1

            git fetch origin main || exit 1
            git reset --hard origin/main || exit 1

            echo "Deployment completed successfully"


              